# Generated by Django 4.1.3 on 2022-11-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_no', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('count', models.IntegerField(default=1)),
                ('course', models.CharField(choices=[('1', 'BCA'), ('2', 'MCA')], default=1, max_length=10)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
