# Generated by Django 4.1.3 on 2022-11-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_students_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='enrollment_no',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
