# Generated by Django 4.1.3 on 2022-11-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_students_enrollment_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='enrollment_no',
            field=models.PositiveIntegerField(),
        ),
    ]
