# Generated by Django 4.1.3 on 2022-11-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_students_enrollment_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='course',
            field=models.CharField(choices=[('1', 'BCA'), ('2', 'MCA')], default=1, max_length=10),
        ),
        migrations.AddField(
            model_name='students',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
