# Generated by Django 4.1.3 on 2022-11-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_students_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='enrollment_no',
            field=models.CharField(max_length=30),
        ),
    ]
